services:
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cobaltdb
      MONGO_INITDB_ROOT_PASSWORD: "-)i8N~x4r9cVX8"
    volumes:
      - ./storage:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 5

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cobaltdb
      ME_CONFIG_MONGODB_ADMINPASSWORD: "-)i8N~x4r9cVX8"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy

  app:
    container_name: cobalt-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx:ro
    depends_on:
      - app
      - mongo-express
